python pred_pe.py R21
python pred_pe.py G23
python pred_pe.py HW
python pred_pe.py WP
python pred_pe.py LJ
python pred_pe.py R24
python pred_pe.py G24
python pred_pe.py G25
python pred_pe.py TW
python pred_pe.py Friendster